"""The sixteen mutation operators of the tree profile.

Each derives, from a correct net generated by pyruleanalyzer's exporter, one
that a named property must reject:

========================  ===========  ==============================================
Mutant                    Must fail    Edit
========================  ===========  ==============================================
``cycle``                 A1           a live leaf gives its input token back instead
                                       of producing its output
``deadlock``              A2, A3       the transition producing the prediction loses
                                       its output arc
``dead_branch``           A4, A8       a dormant leaf is always enabled and produces
                                       nothing: a second, predictionless end
``double_output``         A5, A7       the prediction is deposited twice
``bad_label``             A6           the prediction becomes a label outside L
``overlap``               B1, B4       a dormant leaf becomes enabled next to the
                                       live one
``hidden_overlap``        B4           two dormant leaves get the same guard; the
                                       sample does not reach them, so B1 still holds
``no_leaf``               B2           the live leaf's guard becomes false
``tree_double``           B3           a tree emits its result twice
``skip_stage``            C1           a boosting stage reads the accumulator of the
                                       stage before the previous one
``early_score``           C2           Finalize reads the second-to-last accumulator
``no_decision``           C3a          the live Decide guard becomes false
``two_decisions``         C3b          a dormant Decide guard becomes true
``partial_vote``          D1           Vote stops waiting for the first tree
``no_vote``               D2a          Vote guard becomes false
``wrong_value``           PC           the net predicts another valid class; every
                                       CTL property still holds
========================  ===========  ==============================================

The operators distinguish *live* transitions -- those that occur for the input
in the net's own initial marking -- from *dormant* ones, because a fault in a
branch the input never reaches is invisible to per-input model checking, and
that is what separates the structural technique from the state-space one.
"""

import re
from typing import Dict, List, Optional, Tuple

from cpncheck.coloured import ColouredNet
from cpncheck.mutation import CPNDocument, Mutant
from cpncheck.mutation import make_mutants as _make_mutants
from cpncheck.net import CPNNet
from .cpn_profile import detect_family
from cpncheck.statespace import build_state_space

__all__ = ["CPNDocument", "Mutant", "MUTANTS", "TREE_MUTANTS", "analyse",
           "make_mutants"]


# Function to find which transitions occur for the net's own input.
def analyse(path: str) -> Dict[str, object]:
    """Locate the live and dormant transitions the operators edit.

    Args:
        path (str): A correct generated net.

    Returns:
        dict: Pages, live leaves, dormant leaves, the prediction producer,
        channels and vote information.
    """
    net = CPNNet(path)
    cnet = ColouredNet(net)
    ss = build_state_space(cnet, max_nodes=500_000)
    occurring = {ti for out in ss.succ for ti, _k, _w in out}
    trans = cnet.transitions
    top = cnet.top["name"]
    family = detect_family(cnet)
    trees: Dict[str, Dict[str, List[str]]] = {}
    for ti, t in enumerate(trans):
        is_leaf = t["page"].startswith("Tree") if family != "Decision Tree" \
            else t["page"] == top
        if not is_leaf:
            continue
        info = trees.setdefault(t["page"], {"live": [], "dormant": []})
        info["live" if ti in occurring else "dormant"].append(t["name"])
    pred_idx = next(i for i, p in enumerate(cnet.places)
                    if p["name"] == "Prediction" and p["page"] == top)
    producers = [trans[ti] for ti in occurring
                 if any(p == pred_idx for p, _ in trans[ti]["out"])]
    decides = [t["name"] for t in trans if t["page"] == top
               and t["name"].startswith("Decide")]
    live_decides = [trans[ti]["name"] for ti in occurring
                    if trans[ti]["name"].startswith("Decide")]
    channels = sorted({t["page"] for t in trans if t["name"] == "Finalize"})
    labels = sorted({tok for d in ss.dead for tok in ss.markings[d][pred_idx]})
    domain = set()
    for t in trans:
        for p, terms in t["out"]:
            if p != pred_idx:
                continue
            for _count, code in terms:
                try:
                    value = eval(code, dict(cnet.env))  # noqa: S307
                except Exception:
                    continue
                if isinstance(value, int):
                    domain.add(value)
    return {"family": family, "top": top, "trees": trees, "labels": sorted(domain),
            "producer": producers[0]["name"] if producers else None,
            "producer_page": producers[0]["page"] if producers else None,
            "decides": decides, "live_decides": live_decides,
            "channels": channels, "prediction": labels}


# Function to pick the first tree page with a live leaf.
def _live_tree(info) -> Tuple[str, str]:
    """The first tree page and its live leaf.

    Args:
        info (dict): Output of :func:`analyse`.

    Returns:
        tuple: ``(page, leaf name)``.
    """
    for page, leaves in info["trees"].items():
        if leaves["live"]:
            return page, leaves["live"][0]
    raise LookupError("no live leaf")


# Function to pick a dormant, non-catch-all leaf of a tree page.
def _dormant(info, page: str, n: int = 1) -> Optional[List[str]]:
    """Dormant leaves of a page, excluding the catch-all.

    Args:
        info (dict): Output of :func:`analyse`.
        page (str): Tree page.
        n (int): How many are needed.

    Returns:
        list|None: ``n`` leaf names, or None if the page has fewer.
    """
    names = [t for t in info["trees"][page]["dormant"] if not t.endswith("_default")]
    return names[:n] if len(names) >= n else None


# Function to find a tree page with a live leaf and enough dormant ones.
def _page_with_dormant(info, n: int = 1) -> Optional[Tuple[str, List[str]]]:
    """A tree page whose live leaf has ``n`` dormant, non-catch-all siblings.

    Args:
        info (dict): Output of :func:`analyse`.
        n (int): Dormant leaves needed.

    Returns:
        tuple|None: ``(page, dormant leaf names)``.
    """
    for page, leaves in info["trees"].items():
        if not leaves["live"]:
            continue
        dormant = _dormant(info, page, n)
        if dormant:
            return page, dormant
    return None


# Function to make a live leaf give its token back (A1).
def _cycle(doc: CPNDocument, info) -> bool:
    page, leaf = _live_tree(info)
    inp = doc.arcs(page, leaf, "PtoT")[0]
    for arc in doc.arcs(page, leaf, "TtoP"):
        doc.remove_arc(page, arc)
    place = doc.place(page, doc.place_of(page, inp))
    doc.add_arc(page, inp, "TtoP", doc.trans(page, leaf), place,
                inp.find("annot/text").text)
    return True


# Function to drop the output arc of the prediction producer (A2, A3).
def _deadlock(doc: CPNDocument, info) -> bool:
    page, name = info["producer_page"], info["producer"]
    for arc in doc.arcs(page, name, "TtoP"):
        if doc.place_of(page, arc) == "Prediction":
            doc.remove_arc(page, arc)
    return True


# Function to add an always-enabled dead-end leaf (A4, A8).
def _dead_branch(doc: CPNDocument, info) -> bool:
    found = _page_with_dormant(info)
    if not found:
        return False
    page, dormant = found
    doc.set_guard(page, dormant[0], "[true]")
    for arc in doc.arcs(page, dormant[0], "TtoP"):
        doc.remove_arc(page, arc)
    return True


# Function to deposit the prediction twice (A5, A7).
def _double_output(doc: CPNDocument, info) -> bool:
    page, name = info["producer_page"], info["producer"]
    for arc in doc.arcs(page, name, "TtoP"):
        if doc.place_of(page, arc) == "Prediction":
            e = arc.find("annot/text").text.strip()
            doc.set_inscription(arc, f"1`{e} ++ 1`{e}")
    return True


# Function to deposit a label outside the domain (A6).
def _bad_label(doc: CPNDocument, info) -> bool:
    page, name = info["producer_page"], info["producer"]
    for arc in doc.arcs(page, name, "TtoP"):
        if doc.place_of(page, arc) == "Prediction":
            doc.set_inscription(arc, "7")
    return True


# Function to enable a dormant leaf next to the live one (B1, B4).
def _overlap(doc: CPNDocument, info) -> bool:
    found = _page_with_dormant(info)
    if not found:
        return False
    page, dormant = found
    doc.set_guard(page, dormant[0], "[true]")
    return True


# Function to give two dormant leaves the same guard (B4 only).
def _hidden_overlap(doc: CPNDocument, info) -> bool:
    for page in info["trees"]:
        dormant = _dormant(info, page, 2)
        if dormant:
            doc.set_guard(page, dormant[0], doc.guard(page, dormant[1]))
            return True
    return False


# Function to disable the live leaf of a tree (B2).
def _no_leaf(doc: CPNDocument, info) -> bool:
    page, leaf = _live_tree(info)
    doc.set_guard(page, leaf, "[false]")
    return True


# Function to make a tree emit its result twice (B3).
def _tree_double(doc: CPNDocument, info) -> bool:
    page, leaf = _live_tree(info)
    for arc in doc.arcs(page, leaf, "TtoP"):
        e = arc.find("annot/text").text.strip()
        doc.set_inscription(arc, f"1`{e} ++ 1`{e}")
    return True


# Function to make a stage skip its predecessor (C1).
def _skip_stage(doc: CPNDocument, info) -> bool:
    for page in reversed(info["channels"]):
        try:
            feed2 = doc.arcs(page, "Feed_2", "PtoT")
        except KeyError:
            continue
        for arc in feed2:
            if doc.place_of(page, arc) == "Acc1":
                doc.retarget(arc, doc.place(page, "Acc0"))
                return True
    return False


# Function to finalise a channel before its last stage (C2).
def _early_score(doc: CPNDocument, info) -> bool:
    for page in reversed(info["channels"]):
        accs = sorted(int(m.group(1)) for p in doc.pages[page].findall("place")
                      for m in [re.fullmatch(r"Acc(\d+)",
                                             (p.findtext("text") or "").strip())] if m)
        if len(accs) < 2:
            continue
        for arc in doc.arcs(page, "Finalize", "PtoT"):
            doc.retarget(arc, doc.place(page, f"Acc{accs[-2]}"))
            return True
    return False


# Function to disable the live decision (C3a).
def _no_decision(doc: CPNDocument, info) -> bool:
    if not info["live_decides"]:
        return False
    doc.set_guard(info["top"], info["live_decides"][0], "[false]")
    return True


# Function to enable a second decision (C3b).
def _two_decisions(doc: CPNDocument, info) -> bool:
    dormant = [d for d in info["decides"] if d not in info["live_decides"]]
    if not dormant:
        return False
    doc.set_guard(info["top"], dormant[0], "[true]")
    return True


# Function to make Vote stop waiting for the first tree (D1).
def _partial_vote(doc: CPNDocument, info) -> bool:
    top = info["top"]
    arcs = doc.arcs(top, "Vote", "PtoT")
    first = next((a for a in arcs if a.find("annot/text").text.strip() == "vp0"), None)
    if first is None or len(arcs) < 2:
        return False
    doc.remove_arc(top, first)
    for arc in doc.arcs(top, "Vote", "TtoP"):
        text = arc.find("annot/text").text
        doc.set_inscription(arc, re.sub(r"\[\s*vp0\s*,\s*", "[", text))
    return True


# Function to disable Vote (D2a).
def _no_vote(doc: CPNDocument, info) -> bool:
    doc.set_guard(info["top"], "Vote", "[false]")
    return True


# Function to make the net predict another valid class (PC).
def _wrong_value(doc: CPNDocument, info) -> bool:
    page, name = info["producer_page"], info["producer"]
    current = info["prediction"][0] if info["prediction"] else 0
    other = 1 if current == 0 else 0
    for arc in doc.arcs(page, name, "TtoP"):
        if doc.place_of(page, arc) == "Prediction":
            doc.set_inscription(arc, str(other))
    return True


# Function to build an applicability test from a list of model families.
def _families(*names):
    """An applicability predicate matching the analysed net's family.

    Args:
        *names (str): The families the operator applies to.

    Returns:
        callable: ``info -> bool``.
    """
    return lambda info: info.get("family") in names


_ALL = _families("Decision Tree", "Random Forest",
                 "Gradient Boosting Decision Trees")
_GBDT = _families("Gradient Boosting Decision Trees")
_RF = _families("Random Forest")

#: Every mutation operator of the tree profile, in report order.
TREE_MUTANTS: List[Mutant] = [
    Mutant("cycle", ("A1",), _ALL, "live leaf returns its input token", _cycle),
    Mutant("deadlock", ("A2", "A3"), _ALL,
           "prediction producer loses its output arc", _deadlock),
    Mutant("dead_branch", ("A4", "A8"), _ALL,
           "dormant leaf always enabled, produces nothing", _dead_branch),
    Mutant("double_output", ("A5", "A7"), _ALL,
           "prediction deposited twice", _double_output),
    Mutant("bad_label", ("A6",), _ALL, "prediction replaced by label 7", _bad_label),
    Mutant("overlap", ("B1", "B4"), _ALL,
           "dormant leaf enabled next to the live one", _overlap),
    Mutant("hidden_overlap", ("B4",), _ALL,
           "two dormant leaves share a guard", _hidden_overlap),
    Mutant("no_leaf", ("B2",), _ALL, "live leaf guard set to false", _no_leaf),
    Mutant("tree_double", ("B3",), _ALL, "tree emits its result twice",
           _tree_double),
    Mutant("skip_stage", ("C1",), _GBDT, "Feed_2 reads Acc0", _skip_stage),
    Mutant("early_score", ("C2",), _GBDT, "Finalize reads Acc_{M-1}", _early_score),
    Mutant("no_decision", ("C3a",), _GBDT, "live Decide guard set to false",
           _no_decision),
    Mutant("two_decisions", ("C3b",), _GBDT, "dormant Decide guard set to true",
           _two_decisions),
    Mutant("partial_vote", ("D1",), _RF, "Vote no longer consumes tree 0's vote",
           _partial_vote),
    Mutant("no_vote", ("D2a",), _RF, "Vote guard set to false", _no_vote),
    Mutant("wrong_value", ("PC",), _ALL, "net predicts another valid class",
           _wrong_value),
]


#: Every mutation operator of the generated nets, in report order.
MUTANTS = TREE_MUTANTS


# Function to derive the mutants of a generated net.
def make_mutants(path: str, out_dir: str, names=None, profile=None):
    """CPNCheck's mutant driver, with the label domain under ``labels`` too.

    The generic driver reports the settings a mutant must be checked with
    under ``options``; the tree tests read the label domain as ``labels``.

    Args:
        path (str): The correct ``.cpn``.
        out_dir (str): Where the mutants are written.
        names (list, optional): Restrict to these operators.
        profile (Profile, optional): The profile; the tree profile if omitted.

    Returns:
        list: One dict per mutant written.
    """
    from .cpn_profile import PROFILE

    out = _make_mutants(path, out_dir, names=names, profile=profile or PROFILE)
    for entry in out:
        entry["labels"] = (entry.get("options") or {}).get("class_labels")
    return out
