"""Ask CPN Tools itself: a headless oracle for the model checker.

The model checker in :mod:`pyruleanalyzer.model_checker` builds occurrence
graphs and evaluates CTL formulas in Python. Its answers are only as good as its
agreement with a reference implementation, and the reference for Coloured Petri
Nets is CPN Tools. This module runs CPN Tools' own engine without its GUI and
asks it the same questions:

1. the ``.cpn`` file is loaded and compiled by the CPN Tools 4.0.1 simulator
   (the Standard ML heap image shipped in ``CPN Tools/cpnsim``), driven through
   Access/CPN, the Java library CPN IDE uses to talk to that simulator;
2. the state-space tool is entered exactly as the GUI's *Enter State Space*
   does it -- ``ogpath`` is set and ``switch1.sml`` ... ``switch8.sml`` from
   ``CPN Tools/cpnsim/statespacefiles`` are loaded, which capture the compiled
   net and generate its occurrence-graph code;
3. ``CalculateOccGraph`` and ``CalculateSccGraph`` build the graphs, ASK-CTL is
   loaded, and every query of :meth:`CPNModelChecker.ml_program` is evaluated
   on its own, so one failing query does not hide the others.

Requirements, all found automatically on a Windows machine with CPN Tools and
CPN IDE installed: a 32-bit Java 8 runtime with the Nashorn ``jjs`` launcher,
the Access/CPN libraries bundled in the CPN IDE backend jar, and the CPN Tools
installation. :meth:`CPNToolsOracle.available` reports whether they are present;
nothing else in the package depends on this module.
"""

import glob
import hashlib
import json
import os
import re
import shutil
import socket
import subprocess
import tempfile
import time
import zipfile
from typing import Dict, List, Optional, Tuple

__all__ = ["OracleUnavailable", "CPNToolsOracle", "compare_with_oracle"]

_DRIVER = r"""
// Generated by pyruleanalyzer.cpntools_oracle -- drives the CPN Tools simulator.
var Files = Java.type("java.nio.file.Files");
var Paths = Java.type("java.nio.file.Paths");
var JString = Java.type("java.lang.String");
var File = Java.type("java.io.File");
var job = JSON.parse(new JString(Files.readAllBytes(Paths.get(arguments[0])), "UTF-8"));
var out = { values: {}, errors: {}, log: [] };
function save() {
    Files.write(Paths.get(job.resultFile), new JString(JSON.stringify(out)).getBytes("UTF-8"));
}
var s = null;
try {
    var DOMParser = Java.type("org.cpntools.accesscpn.model.importer.DOMParser");
    var HLS = Java.type("org.cpntools.accesscpn.engine.highlevel.HighLevelSimulator");
    var Checker = Java.type("org.cpntools.accesscpn.engine.highlevel.checker.Checker");
    var net = DOMParser.parse(new File(job.net).toURI().toURL());
    s = HLS.getHighLevelSimulator();
    out.banner = String(s.getBanner());
    var c = new Checker(net, null, s);
    c.checkEntireModel(job.modelDir, job.outDir);
    out.log.push("compiled");
    function ev(code) { return String(s.evaluate(code)); }
    ev("val ogpath = \"" + job.ogpath + "\";");
    for (var i = 1; i <= 8; i++) {
        var r = ev("use (ogpath^\"switch" + i + ".sml\");");
        if (r.indexOf("Error") >= 0 || r.indexOf("uncaught exception") >= 0) {
            out.errors["enter_state_space"] = "switch" + i + ": " + r.substring(0, 2000);
        }
    }
    out.log.push("entered state space");
    var t0 = java.lang.System.currentTimeMillis();
    ev("CalculateOccGraph ();");
    ev("CalculateSccGraph ();");
    out.graph_ms = java.lang.System.currentTimeMillis() - t0;
    ev("use (ogpath^\"ASKCTL/ASKCTLloader.sml\");");
    var d = ev(job.declarations);
    if (d.indexOf("Error") >= 0) { out.errors["declarations"] = d.substring(0, 4000); }
    for (var k = 0; k < job.queries.length; k++) {
        var key = job.queries[k][0], expr = job.queries[k][1];
        var q0 = java.lang.System.currentTimeMillis();
        var res = ev("val pyra_it = " + expr + ";");
        var m = /val pyra_it = "([^"]*)" : string/.exec(res);
        if (m) { out.values[key] = m[1]; } else { out.errors[key] = res.substring(0, 1500); }
        out.log.push(key + " " + (java.lang.System.currentTimeMillis() - q0) + "ms");
    }
} catch (e) {
    out.errors["driver"] = String(e);
} finally {
    save();
    try { if (s !== null) { s.destroy(); } } catch (e2) {}
    java.lang.System.exit(0);
}
"""


# Exception raised when CPN Tools, CPN IDE or Java cannot be found.
class OracleUnavailable(RuntimeError):
    """The CPN Tools engine cannot be run on this machine."""


# Function to convert a Windows path into the cygwin form the simulator expects.
def _cygpath(path: str) -> str:
    """Translate ``C:\\a\\b`` into ``/cygdrive/c/a/b``.

    Args:
        path (str): A Windows path.

    Returns:
        str: The cygwin path.
    """
    path = os.path.abspath(path).replace("\\", "/")
    m = re.match(r"^([A-Za-z]):/(.*)$", path)
    return f"/cygdrive/{m.group(1).lower()}/{m.group(2)}" if m else path


# Class running the CPN Tools engine headlessly.
class CPNToolsOracle:
    """Headless access to the CPN Tools 4.0.1 simulator and state-space tool.

    Example:
        >>> oracle = CPNToolsOracle()
        >>> if oracle.available():
        ...     report = compare_with_oracle("files/gbdt_final.cpn", oracle)
    """

    SIMULATOR_FILES = (
        ("cpnmld.x86-cygwin.exe", "cpnmld.x86-cygwin"),
        ("run.x86-cygwin.exe", "run.x86-cygwin"),
        ("cpn.ML.x86-cygwin", "cpn.ML.x86-cygwin"),
        ("cygwin1.dll", "cygwin1.dll"),
        ("cyggcc_s-1.dll", "cyggcc_s-1.dll"),
    )
    PORT = 20001

    # Method to locate the tools the oracle needs.
    def __init__(self, cpntools_dir: Optional[str] = None,
                 backend_jar: Optional[str] = None, jjs: Optional[str] = None,
                 cache_dir: Optional[str] = None):
        """Find CPN Tools, the Access/CPN libraries and a Nashorn launcher.

        Args:
            cpntools_dir (str, optional): CPN Tools installation directory.
            backend_jar (str, optional): The CPN IDE backend jar, which bundles
                the Access/CPN libraries.
            jjs (str, optional): Path to Java 8's ``jjs``.
            cache_dir (str, optional): Where the libraries and the simulator
                are staged (defaults to a folder in the user's cache).
        """
        pf86 = os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)")
        pf = os.environ.get("ProgramFiles", r"C:\Program Files")
        self.cpntools_dir = cpntools_dir or os.path.join(pf86, "CPN Tools")
        self.backend_jar = backend_jar or next(iter(sorted(glob.glob(os.path.join(
            pf86, "CPN IDE", "resources", "backend", "cpn-ide-back-*.jar")) + glob.glob(
            os.path.join(pf, "CPN IDE", "resources", "backend", "cpn-ide-back-*.jar")))),
            None)
        self.jjs = jjs or next(iter(sorted(glob.glob(os.path.join(
            pf86, "Java", "jre1.8*", "bin", "jjs.exe")) + glob.glob(os.path.join(
            pf, "Java", "jre1.8*", "bin", "jjs.exe")) + glob.glob(os.path.join(
            pf, "Java", "jdk1.8*", "bin", "jjs.exe")))), None)
        base = cache_dir or os.path.join(
            os.environ.get("LOCALAPPDATA", tempfile.gettempdir()),
            "pyruleanalyzer", "cpntools-oracle")
        self.cache_dir = base
        self.lib_dir = os.path.join(base, "lib")
        self.tmp_dir = os.path.join(base, "tmp")
        self.sim_dir = os.path.join(self.tmp_dir, "accesscpn", "simulator")
        self.driver = os.path.join(base, "driver.js")

    # Property returning the CPN Tools simulator directory.
    @property
    def cpnsim(self) -> str:
        """The ``cpnsim`` folder of the CPN Tools installation.

        Returns:
            str: Its path.
        """
        return os.path.join(self.cpntools_dir, "cpnsim")

    # Method to tell whether the oracle can run here.
    def available(self) -> bool:
        """Whether every required component was found.

        Returns:
            bool: True if :meth:`run` can be used.
        """
        return not self.missing()

    # Method to list the missing components.
    def missing(self) -> List[str]:
        """The components that could not be found.

        Returns:
            list: Human-readable names, empty when everything is present.
        """
        out = []
        if not os.path.isfile(os.path.join(self.cpnsim, "cpn.ML.x86-cygwin")):
            out.append(f"CPN Tools simulator in {self.cpnsim}")
        if not os.path.isdir(os.path.join(self.cpnsim, "statespacefiles")):
            out.append("CPN Tools state-space files")
        if not self.backend_jar or not os.path.isfile(self.backend_jar):
            out.append("CPN IDE backend jar (Access/CPN libraries)")
        if not self.jjs or not os.path.isfile(self.jjs):
            out.append("Java 8 jjs (Nashorn)")
        return out

    # Method to prepare libraries, simulator copy and driver script.
    def _stage(self):
        """Extract the Access/CPN libraries and copy the 4.0.1 simulator.

        Access/CPN starts the simulator found in ``<java tmp>/accesscpn/
        simulator`` and only extracts its own bundled one when that folder is
        empty; pointing Java's temp directory at a folder holding CPN Tools'
        files makes it run CPN Tools 4.0.1's simulator.

        Raises:
            OracleUnavailable: If a component is missing.
        """
        missing = self.missing()
        if missing:
            raise OracleUnavailable("missing: " + "; ".join(missing))
        os.makedirs(self.lib_dir, exist_ok=True)
        os.makedirs(self.sim_dir, exist_ok=True)
        if not glob.glob(os.path.join(self.lib_dir, "*.jar")):
            with zipfile.ZipFile(self.backend_jar) as z:
                for name in z.namelist():
                    if name.startswith("BOOT-INF/lib/") and name.endswith(".jar"):
                        with open(os.path.join(self.lib_dir, name.split("/")[-1]),
                                  "wb") as fh:
                            fh.write(z.read(name))
        for src, dst in self.SIMULATOR_FILES:
            target = os.path.join(self.sim_dir, dst)
            source = os.path.join(self.cpnsim, src)
            if not os.path.exists(target) or \
                    os.path.getsize(target) != os.path.getsize(source):
                shutil.copyfile(source, target)
        with open(self.driver, "w", encoding="utf-8") as fh:
            fh.write(_DRIVER)

    # Method to report the identity of the simulator image being used.
    def simulator_digest(self) -> str:
        """SHA-256 of the staged simulator heap image.

        Returns:
            str: The hex digest (records which engine answered).
        """
        self._stage()
        h = hashlib.sha256()
        with open(os.path.join(self.sim_dir, "cpn.ML.x86-cygwin"), "rb") as fh:
            for block in iter(lambda: fh.read(1 << 20), b""):
                h.update(block)
        return h.hexdigest()

    # Method to check that no other simulator daemon owns the port.
    def _port_free(self) -> bool:
        """Whether the simulator daemon port is free.

        A daemon left running by CPN IDE would be reused by Access/CPN and
        would answer with a different simulator image.

        Returns:
            bool: True if nothing listens on the port.
        """
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.settimeout(0.5)
            return sock.connect_ex(("127.0.0.1", self.PORT)) != 0

    # Method to evaluate queries on a net with the CPN Tools engine.
    def run(self, cpn_path: str, declarations: str,
            queries: Dict[str, str], timeout: int = 1800) -> Dict[str, object]:
        """Load, compile and explore a net in CPN Tools, then evaluate queries.

        Args:
            cpn_path (str): The ``.cpn`` file.
            declarations (str): CPN ML declarations evaluated before the queries.
            queries (dict): ``{key: string-valued ML expression}``.
            timeout (int): Seconds before the run is abandoned.

        Returns:
            dict: ``{"values", "errors", "banner", "graph_ms", "elapsed"}``.

        Raises:
            OracleUnavailable: If the engine cannot be started.
        """
        self._stage()
        if not self._port_free():
            raise OracleUnavailable(
                f"port {self.PORT} is in use: close CPN IDE / CPN Tools or end any "
                "cpnmld process, so the CPN Tools 4.0.1 simulator is started")
        cpn_path = os.path.abspath(cpn_path)
        work = tempfile.mkdtemp(prefix="oracle_", dir=self.cache_dir)
        job_file = os.path.join(work, "job.json")
        result_file = os.path.join(work, "result.json")
        out_dir = os.path.join(work, "out")
        os.makedirs(out_dir, exist_ok=True)
        job = {
            "net": cpn_path,
            "modelDir": os.path.dirname(cpn_path) + "\\",
            "outDir": out_dir + "\\",
            "ogpath": _cygpath(os.path.join(self.cpnsim, "statespacefiles")) + "/",
            "declarations": declarations,
            "queries": [[k, v] for k, v in queries.items()],
            "resultFile": result_file,
        }
        with open(job_file, "w", encoding="utf-8") as fh:
            json.dump(job, fh)
        # Nashorn's option parser rejects class-path entries carrying a drive
        # letter, so the jars are given relative to the cache directory.
        classpath = os.pathsep.join(
            "lib/" + os.path.basename(p)
            for p in sorted(glob.glob(os.path.join(self.lib_dir, "*.jar"))))
        cmd = [self.jjs, f"-J-Djava.io.tmpdir={self.tmp_dir}", "-cp", classpath,
               "driver.js", "--", job_file]
        t0 = time.time()
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout,
                              errors="replace", cwd=self.cache_dir)
        elapsed = time.time() - t0
        if not os.path.exists(result_file):
            raise OracleUnavailable("the CPN Tools engine produced no result:\n"
                                    + (proc.stdout + proc.stderr)[-3000:])
        with open(result_file, encoding="utf-8") as fh:
            result = json.load(fh)
        result["elapsed"] = elapsed
        shutil.rmtree(work, ignore_errors=True)
        return result


# Function to compare the model checker with CPN Tools on one net.
def compare_with_oracle(cpn_path: str, oracle: Optional[CPNToolsOracle] = None,
                        class_labels=None, timeout: int = 1800) -> Dict[str, object]:
    """Run both engines on a net and compare every value.

    Args:
        cpn_path (str): The ``.cpn`` file (its own initial marking is used).
        oracle (CPNToolsOracle, optional): The oracle; created when omitted.
        class_labels (list, optional): Label domain for A6.
        timeout (int): Seconds allowed for CPN Tools.

    Returns:
        dict: ``{"net", "rows": [(key, pyra, cpntools, agree)], "agree",
        "errors", "banner", "result"}``.
    """
    from .model_checker import CPNModelChecker

    oracle = oracle or CPNToolsOracle()
    checker = CPNModelChecker(cpn_path, class_labels=class_labels)
    result = checker.check()
    decl, queries = checker.ml_program()
    answer = oracle.run(cpn_path, decl, queries, timeout=timeout)
    rows: List[Tuple[str, str, Optional[str], bool]] = []
    for key in queries:
        mine = result.oracle.get(key)
        theirs = answer["values"].get(key)
        rows.append((key, mine, theirs, mine is not None and mine == theirs))
    return {
        "net": cpn_path, "rows": rows, "agree": all(r[3] for r in rows),
        "errors": answer.get("errors", {}), "banner": answer.get("banner"),
        "graph_ms": answer.get("graph_ms"), "elapsed": answer.get("elapsed"),
        "result": result,
    }
