"""Model checking of the HCPN models generated by the exporter.

CPN Tools answers verification questions interactively: enter the state-space
tool, calculate the occurrence graph and the SCC graph, paste an ASK-CTL script
into an auxiliary box and evaluate it. This module answers the same questions
from Python, on the very ``.cpn`` file CPN Tools would open, so verification can
run on every refinement of every model. Its answers are cross-checked against
CPN Tools itself (see :mod:`pyruleanalyzer.cpntools_oracle`).

Method
------
Four techniques are used, and they are kept apart because they establish
different things:

``ctl``
    Explicit-state CTL model checking (Clarke, Grumberg, Kroening, Peled &
    Veith, *Model Checking*, 2nd ed., MIT Press, 2018; Baier & Katoen,
    *Principles of Model Checking*, MIT Press, 2008). The occurrence graph of
    the Coloured Petri Net is built by :mod:`pyruleanalyzer.cpn_statespace` --
    markings carry real token values, there is no abstraction -- and read as a
    Kripke structure ``K = (S, s0, R, L)``: ``S`` the reachable markings, ``R``
    the occurrences of binding elements, ``L`` the atomic propositions below.
    Formulas are evaluated with the standard fixpoint characterisations
    (``EF``/``E[U]`` as least fixpoints of backward reachability, ``AF`` as the
    least fixpoint of "every successor is in the set").

``scc``
    Home markings, from the decomposition of the occurrence graph into
    strongly connected components: a home marking exists exactly when there is
    a single terminal component (Jensen & Kristensen, *Coloured Petri Nets*,
    Springer, 2009). This is not a CTL formula, and it is what CPN Tools'
    ``ListHomeMarkings`` computes.

``structural``
    Static analysis of the leaf guards, which are conjunctions of axis-aligned
    bounds: two leaves overlap exactly when their boxes intersect. The answer
    holds for every input, which no single state space can show.

``testing``
    Conformance of the net with the classifier on a set of inputs. A
    functional-equivalence test on those inputs, not a temporal property.

Dead markings
-------------
Textbook CTL assumes a total transition relation. The generated nets are meant
to stop, so dead markings are part of the model, and the semantics has to say
what a path formula means when a path ends. Here a dead marking is given a
self-loop (Baier & Katoen, Sec. 3.1), which on the operators used makes a
finite maximal path a counterexample to ``AF phi`` if it ends before ``phi``.

CPN Tools' ASK-CTL does something else: its ``FORALL_UNTIL`` (and so ``EV``)
is *vacuously true* at a dead marking -- the "for all successors" of a node
without successors holds -- so ``EV(phi)`` means ``AF(phi or dead)``. A net that
deadlocks before predicting satisfies ``EV(PRED)``. The two readings differ only
for ``AF``-type properties and only when a dead marking without ``phi`` is
reachable; both are computed, and the ASK-CTL scripts generated here encode
``AF phi`` as ``EV(phi) AND NOT E[not phi U (dead and not phi)]`` so that CPN
Tools answers the textbook question.

Properties
----------
===== ============================== ==================================== ==========
ID    Property                       Formula                              Method
===== ============================== ==================================== ==========
A1    Termination                    AF dead                              ctl
A2    No spurious deadlock           !EF(dead & !pred)                    ctl
A3    Inevitable decision            AF pred                              ctl
A4    Prediction recoverability      AG EF pred                           ctl
A5    Unique output                  AG |Prediction| <= 1                 ctl
A6    Valid label                    AG Prediction subset L               ctl
A7    Safeness                       AG forall p: |p| <= 1                ctl
A8    Home marking                   one terminal SCC                     scc
B1    Leaf determinism               forall T: AG |EN(leaves_T)| <= 1     ctl
B2    Inevitable leaf selection      forall T: AF EN(leaves_T)            ctl
B3    Single tree output             forall T: AG |out_T| <= 1            ctl
B4    Guard disjointness             forall T, i!=j: box_i & box_j = {}   structural
C1    Stage precedence               forall k,m: !E[!acc_k,m-1 U acc_k,m] ctl
C2    No premature score             forall k: !E[!acc_k,M U score_k]     ctl
C3a   Inevitable decision firing     AF EN(decide)                        ctl
C3b   Decision determinism           AG |EN(decide)| <= 1                 ctl
D1    Complete vote                  AG(EN(vote) -> all votes present)    ctl
D2a   Inevitable aggregation         AF EN(vote)                          ctl
D2b   Single aggregation             AG |Prediction| <= 1                 ctl
PC    Prediction consistency         net(x) = model(x)                    testing
===== ============================== ==================================== ==========

``EN(G)`` holds in a marking with an outgoing arc whose transition is in ``G``;
``|EN(G)|`` counts those arcs. ``T`` ranges over tree subpages, ``k`` over GBDT
class channels, ``m`` over boosting stages.
"""

import collections
import os
import re
import time
from typing import Any, Dict, List, Optional, Sequence, Tuple

from .cpn_semantics import CPNNet
from .cpn_statespace import ColouredNet, StateSpace, build_state_space

__all__ = [
    "Property",
    "PROPERTY_CATALOG",
    "METHODS",
    "PropertyResult",
    "ModelCheckResult",
    "CPNModelChecker",
    "check_cpn",
    "compare_results",
]

#: Maximum number of markings explored before giving up on a state space.
DEFAULT_MAX_NODES = 200_000

#: Human-readable names of the verification techniques.
METHODS = collections.OrderedDict((
    ("ctl", "CTL model checking on the occurrence graph"),
    ("scc", "SCC analysis of the occurrence graph"),
    ("structural", "Structural guard analysis (every input)"),
    ("testing", "Conformance testing against the classifier"),
))

_ALL = ("Decision Tree", "Random Forest", "Gradient Boosting Decision Trees")
_GBDT = ("Gradient Boosting Decision Trees",)
_RF = ("Random Forest",)


# Class describing one verifiable property of the generated nets.
class Property:
    """One entry of the property catalog.

    Attributes:
        id (str): Identifier used by the article (``A1``, ``B2``, ``C3a``, ...).
        name (str): Short name.
        ctl (str): The formula the check implements (ASCII).
        kind (str): ``"desired"``, ``"undesired"`` or ``"structural"``.
        families (tuple): Model families the property applies to.
        description (str): What the property guarantees -- and only that.
        method (str): One of :data:`METHODS`.
    """

    __slots__ = ("id", "name", "ctl", "kind", "families", "description", "method")

    # Method to build a catalog entry.
    def __init__(self, id, name, ctl, kind, families, description, method="ctl"):
        """Create a property descriptor.

        Args:
            id (str): Property identifier.
            name (str): Short name.
            ctl (str): Formula.
            kind (str): Category.
            families (tuple): Applicable families.
            description (str): Guarantee.
            method (str): Verification technique.
        """
        self.id = id
        self.name = name
        self.ctl = ctl
        self.kind = kind
        self.families = families
        self.description = description
        self.method = method

    # Method to render the descriptor for debugging.
    def __repr__(self):
        """Return a short representation.

        Returns:
            str: ``<Property A1 Termination>``.
        """
        return f"<Property {self.id} {self.name}>"


#: Every property the checker knows about, in report order.
PROPERTY_CATALOG: "collections.OrderedDict[str, Property]" = collections.OrderedDict()
for _p in (
    Property("A1", "Termination", "AF dead", "desired", _ALL,
             "Every maximal occurrence sequence is finite: no reachable cycle."),
    Property("A2", "No spurious deadlock", "!EF(dead & !pred)", "undesired", _ALL,
             "Every reachable dead marking holds a prediction."),
    Property("A3", "Inevitable decision", "AF pred", "desired", _ALL,
             "On every maximal occurrence sequence Prediction becomes marked."),
    Property("A4", "Prediction recoverability", "AG EF pred", "desired", _ALL,
             "From every reachable marking a marking with a prediction is "
             "reachable. This is not a home-marking property; see A8."),
    Property("A5", "Unique output", "AG |Prediction| <= 1", "undesired", _ALL,
             "Prediction never holds more than one token."),
    Property("A6", "Valid label", "AG Prediction subset L", "undesired", _ALL,
             "Every token ever deposited in Prediction belongs to the declared "
             "label domain L."),
    Property("A7", "Safeness", "AG forall p: |p| <= 1", "structural", _ALL,
             "Every place holds at most one token in every reachable marking."),
    Property("A8", "Home marking", "one terminal SCC", "desired", _ALL,
             "Some marking is reachable from every reachable marking.",
             method="scc"),
    Property("B1", "Leaf determinism", "forall T: AG |EN(leaves_T)| <= 1",
             "undesired", _ALL,
             "For the input in the initial marking, no reachable marking enables "
             "two leaf occurrences of the same tree."),
    Property("B2", "Inevitable leaf selection", "forall T: AF EN(leaves_T)",
             "desired", _ALL,
             "Every tree inevitably reaches a marking where one of its leaves is "
             "enabled."),
    Property("B3", "Single tree output", "forall T: AG |out_T| <= 1",
             "structural", _ALL,
             "The output place of every tree holds at most one token."),
    Property("B4", "Guard disjointness", "forall T, i!=j: box_i & box_j = {}",
             "undesired", _ALL,
             "No two leaf guards of the same tree are satisfiable together, for "
             "any input: the leaves partition the feature space.",
             method="structural"),
    Property("C1", "Stage precedence", "forall k,m: !E[!acc(k,m-1) U acc(k,m)]",
             "undesired", _GBDT,
             "In every class channel, stage m is never completed before stage "
             "m-1 has been."),
    Property("C2", "No premature score", "forall k: !E[!acc(k,M) U score(k)]",
             "undesired", _GBDT,
             "A channel's score appears only after its last stage completed."),
    Property("C3a", "Inevitable decision firing", "AF EN(decide)", "desired", _GBDT,
             "A Decide transition inevitably becomes enabled."),
    Property("C3b", "Decision determinism", "AG |EN(decide)| <= 1", "undesired",
             _GBDT,
             "No reachable marking enables two Decide occurrences."),
    Property("D1", "Complete vote", "AG(EN(vote) -> votes_all)", "undesired", _RF,
             "Vote is only enabled when every tree has voted."),
    Property("D2a", "Inevitable aggregation", "AF EN(vote)", "desired", _RF,
             "Vote inevitably becomes enabled."),
    Property("D2b", "Single aggregation", "AG |Prediction| <= 1", "structural", _RF,
             "The aggregation deposits at most one class (same formula as A5)."),
    Property("PC", "Prediction consistency", "net(x) = model(x)", "desired", _ALL,
             "On the tested inputs, the class the net computes equals the "
             "classifier's.", method="testing"),
):
    PROPERTY_CATALOG[_p.id] = _p
del _p

#: The AF-type properties, for which ASK-CTL's EV reading is also reported.
AF_PROPERTIES = ("A3", "B2", "C3a", "D2a")


# Class holding the verdict of one property.
class PropertyResult:
    """The outcome of checking a single property.

    Attributes:
        id (str): Property identifier.
        holds (bool|None): ``True``/``False``, or ``None`` when not evaluated.
        detail (str): Counterexample, witness or reason for skipping.
        elapsed (float): Seconds spent evaluating the property.
    """

    __slots__ = ("id", "holds", "detail", "elapsed")

    # Method to build a property verdict.
    def __init__(self, id, holds, detail="", elapsed=0.0):
        """Create a verdict.

        Args:
            id (str): Property identifier.
            holds (bool|None): The verdict.
            detail (str): Evidence, counterexample or reason.
            elapsed (float): Evaluation time in seconds.
        """
        self.id = id
        self.holds = holds
        self.detail = detail
        self.elapsed = elapsed

    # Property returning the catalog entry behind this verdict.
    @property
    def spec(self) -> Property:
        """The catalog descriptor.

        Returns:
            Property: The matching entry.
        """
        return PROPERTY_CATALOG[self.id]

    # Property returning the printable status of the verdict.
    @property
    def status(self) -> str:
        """Status label.

        Returns:
            str: ``"PASS"``, ``"FAIL"`` or ``"SKIP"``.
        """
        return "SKIP" if self.holds is None else ("PASS" if self.holds else "FAIL")

    # Method to render the verdict for debugging.
    def __repr__(self):
        """Return a short representation.

        Returns:
            str: ``<A1 PASS>``.
        """
        return f"<{self.id} {self.status}>"


# Class aggregating every verdict produced for one .cpn model.
class ModelCheckResult:
    """The outcome of verifying one generated ``.cpn``.

    Attributes:
        path (str): The checked file.
        family (str): Detected model family.
        properties (dict): ``{id: PropertyResult}``.
        stats (dict): State-space statistics of the first verified input.
        samples (int): Inputs model checked.
        tested (int): Inputs used for conformance testing.
        warnings (list): Non-fatal problems.
        oracle (dict): The values CPN Tools is expected to print for the input
            in the file's initial marking (see :mod:`cpntools_oracle`).
    """

    # Method to build a model-checking result.
    def __init__(self, path, family, properties, stats, samples=1, tested=0,
                 warnings=None, elapsed=0.0, oracle=None):
        """Create a result.

        Args:
            path (str): Checked model.
            family (str): Model family.
            properties (dict): Verdicts.
            stats (dict): State-space statistics.
            samples (int): Inputs model checked.
            tested (int): Inputs used for conformance testing.
            warnings (list, optional): Warnings.
            elapsed (float): Total time in seconds.
            oracle (dict, optional): Expected CPN Tools values.
        """
        self.path = path
        self.family = family
        self.properties = properties
        self.stats = stats
        self.samples = samples
        self.tested = tested
        self.warnings = list(warnings or [])
        self.elapsed = elapsed
        self.oracle = dict(oracle or {})

    # Property telling whether every evaluated property holds.
    @property
    def passed(self) -> bool:
        """Whether no evaluated property was violated.

        Returns:
            bool: True if nothing failed (skipped properties do not count).
        """
        return all(r.holds is not False for r in self.properties.values())

    # Property listing the violated properties.
    @property
    def failures(self) -> List[PropertyResult]:
        """Violated properties.

        Returns:
            list: Results whose verdict is False.
        """
        return [r for r in self.properties.values() if r.holds is False]

    # Property listing the properties that could not be evaluated.
    @property
    def skipped(self) -> List[PropertyResult]:
        """Properties without a verdict.

        Returns:
            list: Results whose verdict is None.
        """
        return [r for r in self.properties.values() if r.holds is None]

    # Method to allow using the result in a boolean test.
    def __bool__(self):
        """Truth value.

        Returns:
            bool: Same as :attr:`passed`.
        """
        return self.passed

    # Method to convert the result into a plain dictionary.
    def to_dict(self) -> Dict[str, Any]:
        """Serialise the result.

        Returns:
            dict: JSON-friendly representation.
        """
        return {
            "path": self.path, "family": self.family, "passed": self.passed,
            "samples": self.samples, "tested": self.tested,
            "elapsed": self.elapsed, "stats": self.stats,
            "warnings": self.warnings, "oracle": self.oracle,
            "properties": {
                pid: {"name": r.spec.name, "formula": r.spec.ctl,
                      "method": r.spec.method, "kind": r.spec.kind,
                      "holds": r.holds, "status": r.status, "detail": r.detail,
                      "elapsed": r.elapsed}
                for pid, r in self.properties.items()
            },
        }

    # Method to render the result as a plain-text report.
    def report(self, show_formula: bool = True) -> str:
        """Build a human-readable report, grouped by technique.

        Args:
            show_formula (bool): Include the formula column.

        Returns:
            str: The report.
        """
        lines = []
        head = f"Model checking: {os.path.basename(self.path)}  [{self.family}]"
        lines.append(head)
        lines.append("=" * max(len(head), 76))
        st = self.stats
        if st.get("nodes") is not None:
            lines.append(f"  occurrence graph : {st['nodes']} nodes, {st['arcs']} arcs"
                         f"{'' if st.get('complete', True) else ' (INCOMPLETE)'}")
            if st.get("complete", True):
                lines.append(f"  SCC graph        : {st.get('scc_nodes')} nodes, "
                             f"{st.get('scc_arcs')} arcs, {st.get('dead')} dead "
                             f"marking(s), {st.get('home')} home marking(s)")
        lines.append(f"  inputs           : {self.samples} model checked, "
                     f"{self.tested} tested   time: {self.elapsed:.2f}s")
        lines.append("  semantics        : CTL over the occurrence graph, dead "
                     "markings with a self-loop")
        for method, title in METHODS.items():
            rows = [r for r in self.properties.values() if r.spec.method == method]
            if not rows:
                continue
            lines.append("")
            lines.append(f"  {title}")
            lines.append("  " + "-" * 78)
            for r in rows:
                row = f"  {r.id:<5}{r.spec.name:<29}"
                if show_formula:
                    row += f"{r.spec.ctl:<41}"
                row += r.status
                lines.append(row)
                if r.detail and r.holds is not True:
                    lines.append(f"        -> {r.detail}")
        lines.append("")
        n_pass = sum(1 for r in self.properties.values() if r.holds is True)
        lines.append(f"  {n_pass} passed, {len(self.failures)} failed, "
                     f"{len(self.skipped)} skipped -- "
                     f"{'VERIFIED' if self.passed else 'VIOLATION FOUND'}")
        for w in self.warnings:
            lines.append(f"  [warning] {w}")
        return "\n".join(lines)

    # Method to escape a formula for a LaTeX texttt cell.
    @staticmethod
    def _latex_escape(text: str) -> str:
        """Make a formula safe inside ``\\texttt{...}``.

        Args:
            text (str): The formula.

        Returns:
            str: The escaped formula.
        """
        table = {"_": r"\_", "{": r"\{", "}": r"\}", "&": r"\&", "%": r"\%",
                 "$": r"\$", "#": r"\#", "|": r"\textbar{}",
                 "<": r"\textless{}", ">": r"\textgreater{}",
                 "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
        return "".join(table.get(ch, ch) for ch in text)

    # Method to render the verdicts as LaTeX table rows.
    def latex_rows(self) -> str:
        """LaTeX rows ``ID & Property & Formula & Method & Result & Time``.

        The result column uses ``\\cmark`` / ``\\xmark``, which the preamble
        must define (``pifont``'s ``\\ding{51}`` and ``\\ding{55}``).

        Returns:
            str: One row per property.
        """
        out = []
        for pid, r in self.properties.items():
            res = {"PASS": r"\cmark", "FAIL": r"\xmark", "SKIP": "--"}[r.status]
            out.append(f"{pid} & {r.spec.name} & "
                       f"\\texttt{{{self._latex_escape(r.spec.ctl)}}} & "
                       f"{r.spec.method} & {res} & {r.elapsed:.3f} \\\\")
        return "\n".join(out)

    # Method to render the verdicts as a complete LaTeX table.
    def latex_table(self, label: str = "tab:model_checking",
                    caption: Optional[str] = None) -> str:
        """The whole results table, ready to paste.

        Args:
            label (str): ``\\label`` of the table.
            caption (str, optional): Caption; a default names the model and
                the size of the occurrence graph.

        Returns:
            str: A ``table`` environment.
        """
        if caption is None:
            st = self.stats
            size = (f" (occurrence graph: {st['nodes']} nodes, {st['arcs']} arcs)"
                    if st.get("nodes") else "")
            caption = (f"Verification results for the generated {self.family} "
                       f"net{size}; {self.samples} input(s) model checked.")
        return "\n".join([
            r"\begin{table}[t]", r"\centering",
            f"\\caption{{{caption}}}", f"\\label{{{label}}}",
            r"\begin{tabular}{@{}lllllr@{}}", r"\toprule",
            r"ID & Property & Formula & Method & Result & Time (s) \\",
            r"\midrule", self.latex_rows(), r"\bottomrule",
            r"\end{tabular}", r"\end{table}",
        ])

    # Method to render the result for debugging.
    def __repr__(self):
        """Return a short representation.

        Returns:
            str: ``<ModelCheckResult x.cpn VERIFIED 18/18>``.
        """
        ok = sum(1 for r in self.properties.values() if r.holds is True)
        return (f"<ModelCheckResult {os.path.basename(self.path)} "
                f"{'VERIFIED' if self.passed else 'VIOLATION'} "
                f"{ok}/{len(self.properties)}>")


# ---------------------------------------------------------------------------
# CTL on an occurrence graph
# ---------------------------------------------------------------------------

# Function to compute the nodes satisfying E[hold U target].
def _eu(ss: StateSpace, hold: set, target: set) -> set:
    """Least fixpoint of ``target or (hold and EX Z)``, by backward search.

    Args:
        ss (StateSpace): The graph.
        hold (set): Nodes satisfying the left operand.
        target (set): Nodes satisfying the right operand.

    Returns:
        set: Nodes satisfying ``E[hold U target]``.
    """
    sat = set(target)
    stack = list(target)
    while stack:
        v = stack.pop()
        for _ti, u in ss.pred[v]:
            if u not in sat and u in hold:
                sat.add(u)
                stack.append(u)
    return sat


# Function to compute the nodes satisfying AF target under a chosen semantics.
def _af(ss: StateSpace, target: set, semantics: str = "textbook") -> set:
    """Least fixpoint of ``target or AX Z``.

    Args:
        ss (StateSpace): The graph.
        target (set): Nodes satisfying the operand.
        semantics (str): ``"textbook"`` -- a dead marking has a self-loop, so a
            dead marking outside ``target`` falsifies ``AF`` -- or ``"askctl"``
            -- ASK-CTL's ``EV``, where a dead marking satisfies it vacuously.

    Returns:
        set: Nodes satisfying the formula.
    """
    n = ss.n_nodes
    sat = [False] * n
    remaining = [0] * n
    queue = collections.deque()
    for v in range(n):
        if v in target:
            sat[v] = True
            queue.append(v)
        elif not ss.succ[v]:
            if semantics == "askctl":
                sat[v] = True
                queue.append(v)
            else:
                remaining[v] = -1
        else:
            remaining[v] = len(ss.succ[v])
    while queue:
        w = queue.popleft()
        for _ti, u in ss.pred[w]:
            if sat[u] or remaining[u] < 0:
                continue
            remaining[u] -= 1
            if remaining[u] == 0:
                sat[u] = True
                queue.append(u)
    return {v for v in range(n) if sat[v]}


# Function to find a path witnessing E[hold U target] from the initial node.
def _eu_witness(ss: StateSpace, hold: set, target: set) -> Optional[str]:
    """Shortest occurrence sequence through ``hold`` nodes into ``target``.

    Args:
        ss (StateSpace): The graph.
        hold (set): Nodes allowed before the target.
        target (set): Goal nodes.

    Returns:
        str|None: The transition sequence, or None if there is no witness.
    """
    parent = {0: None}
    queue = collections.deque([0])
    while queue:
        v = queue.popleft()
        if v in target:
            steps = []
            while parent[v] is not None:
                v, name = parent[v]
                steps.append(name)
            steps.reverse()
            if len(steps) > 12:
                steps = steps[:3] + [f"... {len(steps) - 6} more ..."] + steps[-3:]
            return " -> ".join(steps) if steps else "(initial marking)"
        if v not in hold:
            continue
        for ti, _key, w in ss.succ[v]:
            if w not in parent:
                parent[w] = (v, ss.net.transitions[ti]["name"])
                queue.append(w)
    return None


# ---------------------------------------------------------------------------
# What the properties talk about
# ---------------------------------------------------------------------------

# Class locating the places and transitions the properties refer to.
class _Structure:
    """Places and transitions named by the atomic propositions.

    Attributes:
        pred (int): Index of the top-level Prediction place.
        input (int): Index of the top-level Input place.
        trees (OrderedDict): Tree page -> ``{"leaves": [ti], "out": pidx}``.
        channels (OrderedDict): Channel page -> ``{"acc": [pidx], "score": pidx}``.
        decides (list): Decide transition indices.
        vote (list): Vote transition indices.
        vote_socks (list): Output places of every tree -- what "every tree
            has voted" refers to. Defined by the trees, not by Vote's own input
            arcs, so a Vote that stops waiting for a tree is caught.
    """

    # Method to derive the structure from a coloured net.
    def __init__(self, cnet: ColouredNet):
        """Locate every place and transition the properties need.

        Args:
            cnet (ColouredNet): The flattened net.
        """
        top = cnet.top["name"]
        self.top = top
        places, trans = cnet.places, cnet.transitions
        self.pred = next(i for i, p in enumerate(places)
                         if p["name"] == "Prediction" and p["page"] == top)
        self.input = next(i for i, p in enumerate(places)
                          if p["name"] == "Input" and p["page"] == top)

        self.trees: "collections.OrderedDict[str, dict]" = collections.OrderedDict()
        for ti, t in enumerate(trans):
            page = t["page"]
            is_leaf = (page.startswith("Tree") if cnet.family != "Decision Tree"
                       else page == top)
            if not is_leaf:
                continue
            self.trees.setdefault(page, {"leaves": [], "out": None})
            self.trees[page]["leaves"].append(ti)
        for info in self.trees.values():
            outs = {p for ti in info["leaves"] for p, _ in trans[ti]["out"]}
            info["out"] = sorted(outs)[0] if len(outs) == 1 else None

        self.channels: "collections.OrderedDict[str, dict]" = collections.OrderedDict()
        for t in trans:
            if t["name"] != "Finalize":
                continue
            page = t["page"]
            accs = sorted((int(m.group(1)), i) for i, p in enumerate(places)
                          if p["page"] == page
                          for m in [re.fullmatch(r"Acc(\d+)", p["name"])] if m)
            self.channels[page] = {"acc": [i for _, i in accs],
                                   "score": t["out"][0][0] if t["out"] else None}

        self.decides = [ti for ti, t in enumerate(trans)
                        if t["page"] == top and t["name"].startswith("Decide")]
        self.vote = [ti for ti, t in enumerate(trans)
                     if t["page"] == top and t["name"] == "Vote"]
        self.vote_socks = ([info["out"] for info in self.trees.values()
                            if info["out"] is not None] if self.vote else [])


# ---------------------------------------------------------------------------
# The checker
# ---------------------------------------------------------------------------

# Class performing model checking on a generated .cpn file.
class CPNModelChecker:
    """Model checker for the HCPN models written by :mod:`cpn_tools_exporter`.

    The net is read back from the ``.cpn`` file, never from the exporter's
    Python objects, so a disagreement between the net and the classifier is a
    real one.

    Example:
        >>> mc = CPNModelChecker("files/gbdt_final.cpn", class_labels=[0, 1])
        >>> mc.check().passed
        True
    """

    # Method to load a generated .cpn model.
    def __init__(self, path: str, feature_names: Optional[Sequence[str]] = None,
                 class_labels: Optional[Sequence[int]] = None,
                 max_nodes: int = DEFAULT_MAX_NODES):
        """Parse and flatten a ``.cpn`` file.

        Args:
            path (str): The generated model.
            feature_names (list, optional): Ordered feature names, to map named
                samples onto the record fields ``f0``, ``f1``, ...
            class_labels (list, optional): The label domain for A6. Without it
                the domain is read from the net where the net determines it
                (Decide transitions, probability-vector width); for a Decision
                Tree it cannot be, and A6 is skipped.
            max_nodes (int): Occurrence-graph budget; beyond it the state-space
                properties get no verdict.
        """
        self.path = path
        self.net = CPNNet(path)
        self.cnet = ColouredNet(self.net)
        self.family = self.cnet.family
        self.structure = _Structure(self.cnet)
        self.feature_names = list(feature_names) if feature_names else None
        self.max_nodes = int(max_nodes)
        self.labels, self.label_source = self._label_domain(class_labels)
        own = self.cnet.initial[self.structure.input]
        self.own_sample = own[0] if own else None
        self.width = len(self.own_sample) if self.own_sample else 0

    # ------------------------------------------------------------------
    # Inputs
    # ------------------------------------------------------------------

    # Method to determine the label domain used by A6.
    def _label_domain(self, class_labels) -> Tuple[Optional[List[int]], str]:
        """Choose the label domain and say where it came from.

        Args:
            class_labels (list, optional): Declared labels.

        Returns:
            tuple: ``(labels or None, source)``.
        """
        if class_labels is not None:
            try:
                return sorted({int(c) for c in class_labels}), "declared"
            except (TypeError, ValueError):
                pass
        trans = self.cnet.transitions
        if self.family == "Gradient Boosting Decision Trees":
            ks = [int(trans[ti]["name"].rsplit("_", 1)[-1])
                  for ti in self.structure.decides
                  if trans[ti]["name"].rsplit("_", 1)[-1].isdigit()]
            if ks:
                return sorted(ks), "Decide transitions"
        if self.family == "Random Forest":
            for info in self.structure.trees.values():
                for ti in info["leaves"]:
                    for _p, terms in trans[ti]["out"]:
                        try:
                            vec = eval(terms[0][1], dict(self.cnet.env))  # noqa: S307
                        except Exception:
                            continue
                        if isinstance(vec, (tuple, list)) and vec:
                            return list(range(len(vec))), "probability-vector width"
        return None, "undeclared"

    # Method to normalise a sample into the net's record layout.
    def as_sample(self, x) -> Tuple[float, ...]:
        """Convert an input into the tuple of ``SAMPLE`` record fields.

        Args:
            x: A dict keyed by ``f<i>`` or by feature name, a pandas Series, or
                a positional sequence.

        Returns:
            tuple: The field values, in field order.

        Raises:
            ValueError: If the sample has the wrong number of features.
        """
        if isinstance(x, tuple) and all(isinstance(v, float) for v in x):
            values = list(x)
        elif isinstance(x, dict):
            if all(str(k).startswith("f") and str(k)[1:].isdigit() for k in x):
                values = [float(x[f"f{i}"]) for i in range(len(x))]
            else:
                names = self.feature_names or list(x.keys())
                values = [float(x[n]) for n in names]
        else:
            raw = getattr(x, "values", x)
            values = [float(v) for v in list(raw)]
        if self.width and len(values) != self.width:
            raise ValueError(f"sample has {len(values)} features, the net's "
                             f"SAMPLE record has {self.width}")
        return tuple(values)

    # Method to turn the samples argument into a list of record tuples.
    def _sample_list(self, samples) -> List[Optional[Tuple[float, ...]]]:
        """Normalise ``samples``; None means the file's own initial marking.

        Args:
            samples: None, one sample, a list of samples or a DataFrame.

        Returns:
            list: Record tuples (``None`` stands for the file's own input).
        """
        if samples is None:
            return [None]
        if hasattr(samples, "iloc") and hasattr(samples, "columns"):
            return [self.as_sample(samples.iloc[i]) for i in range(len(samples))]
        if isinstance(samples, dict):
            return [self.as_sample(samples)]
        if isinstance(samples, (list, tuple)) and samples and \
                not isinstance(samples[0], (int, float)):
            return [self.as_sample(s) for s in samples]
        return [self.as_sample(samples)]

    # ------------------------------------------------------------------
    # State space
    # ------------------------------------------------------------------

    # Method to build the occurrence graph for one input.
    def state_space(self, sample=None) -> StateSpace:
        """Build the occurrence graph with ``sample`` in the initial marking.

        Args:
            sample: A sample, or None for the file's own initial marking.

        Returns:
            StateSpace: The occurrence graph.
        """
        initial = (None if sample is None
                   else self.cnet.initial_marking(self.as_sample(sample)))
        return build_state_space(self.cnet, self.max_nodes, initial=initial)

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    # Method to evaluate every CTL and SCC property on one occurrence graph.
    def _evaluate(self, ss: StateSpace) -> Tuple[Dict[str, PropertyResult],
                                                 Dict[str, str]]:
        """Evaluate the state-space properties and the expected oracle values.

        Args:
            ss (StateSpace): A complete occurrence graph.

        Returns:
            tuple: ``({id: PropertyResult}, {oracle key: value})``.
        """
        S = self.structure
        net = self.cnet
        n = ss.n_nodes
        nodes = set(range(n))
        dead = set(ss.dead)
        res: Dict[str, PropertyResult] = {}
        oracle: Dict[str, str] = {
            "nodes": str(n), "arcs": str(ss.n_arcs), "scc_nodes": str(ss.n_sccs),
            "scc_arcs": str(ss.n_scc_arcs), "dead": str(len(dead)),
            "home": str(len(ss.home)),
        }

        def cnt(v, p):
            return len(ss.markings[v][p])

        def en(v, group):
            return sum(1 for ti, _k, _w in ss.succ[v] if ti in group)

        def first(bad):
            for v in range(n):
                if bad(v):
                    return v
            return None

        def run(pid, fn):
            t0 = time.perf_counter()
            holds, detail = fn()
            res[pid] = PropertyResult(pid, holds, detail, time.perf_counter() - t0)
            oracle[pid] = "true" if holds else "false"

        def af_check(target, what):
            if 0 in _af(ss, target, "textbook"):
                return True, ""
            w = _eu_witness(ss, nodes - target, dead - target)
            if w is not None:
                return False, f"{what} never happens on: {w}"
            return False, f"a reachable cycle avoids {what}"

        def ag_check(bad, what):
            v = first(bad)
            if v is None:
                return True, ""
            return False, f"{what} after: {ss.trace(v)}"

        pred = {v for v in range(n) if cnt(v, S.pred) > 0}

        # ---- common ------------------------------------------------------
        run("A1", lambda: af_check(dead, "termination"))
        run("A2", lambda: ag_check(lambda v: v in dead and v not in pred,
                                   "dead marking without a prediction"))
        run("A3", lambda: af_check(pred, "the prediction"))
        oracle["A3_ev"] = "true" if 0 in _af(ss, pred, "askctl") else "false"

        def a4():
            missing = nodes - _eu(ss, nodes, pred)
            if not missing:
                return True, ""
            return False, (f"{len(missing)} marking(s) cannot reach a prediction, "
                           f"e.g. after: {ss.trace(min(missing))}")
        run("A4", a4)
        run("A5", lambda: ag_check(lambda v: cnt(v, S.pred) > 1,
                                   "Prediction holds more than one token"))
        if self.labels is not None:
            domain = set(self.labels)
            run("A6", lambda: ag_check(
                lambda v: any(tok not in domain for tok in ss.markings[v][S.pred]),
                f"a label outside {sorted(domain)} is deposited"))
        else:
            res["A6"] = PropertyResult("A6", None, "label domain not declared; "
                                       "pass class_labels")
        run("A7", lambda: ag_check(
            lambda v: any(len(toks) > 1 for toks in ss.markings[v]),
            "a place holds more than one token"))

        def a8():
            if ss.home:
                return True, (f"{len(ss.home)} home marking(s), "
                              f"{len(ss.terminal_sccs)} terminal SCC")
            return False, (f"{len(ss.terminal_sccs)} terminal SCCs: no marking is "
                           "reachable from all others")
        run("A8", a8)

        # ---- trees -------------------------------------------------------
        if S.trees:
            groups = [set(info["leaves"]) for info in S.trees.values()]
            pages = list(S.trees)

            def b1():
                for page, g in zip(pages, groups):
                    v = first(lambda v, g=g: en(v, g) > 1)
                    if v is not None:
                        names = [net.transitions[ti]["name"] for ti, _k, _w
                                 in ss.succ[v] if ti in g]
                        return False, (f"{page}: {', '.join(names[:3])} enabled "
                                       f"together after: {ss.trace(v)}")
                return True, ""
            run("B1", b1)

            def b2(semantics):
                for page, g in zip(pages, groups):
                    target = {v for v in range(n) if en(v, g) > 0}
                    if 0 not in _af(ss, target, semantics):
                        w = _eu_witness(ss, nodes - target, dead - target)
                        return False, (f"{page}: no leaf becomes enabled on: "
                                       f"{w or 'a cycle'}")
                return True, ""
            run("B2", lambda: b2("textbook"))
            oracle["B2_ev"] = "true" if b2("askctl")[0] else "false"

            outs = [info["out"] for info in S.trees.values() if info["out"] is not None]
            run("B3", lambda: ag_check(lambda v: any(cnt(v, p) > 1 for p in outs),
                                       "a tree output place holds two tokens"))

        # ---- GBDT --------------------------------------------------------
        if S.channels:
            def c1():
                for page, ch in S.channels.items():
                    for a, b in zip(ch["acc"], ch["acc"][1:]):
                        hold = {v for v in range(n) if cnt(v, a) == 0}
                        target = {v for v in range(n) if cnt(v, b) > 0}
                        if 0 in _eu(ss, hold, target):
                            w = _eu_witness(ss, hold, target)
                            return False, (f"{page}: {net.places[b]['name']} "
                                           f"reached before {net.places[a]['name']}"
                                           f": {w}")
                return True, ""
            run("C1", c1)

            def c2():
                for page, ch in S.channels.items():
                    if not ch["acc"] or ch["score"] is None:
                        continue
                    last = ch["acc"][-1]
                    hold = {v for v in range(n) if cnt(v, last) == 0}
                    target = {v for v in range(n) if cnt(v, ch["score"]) > 0}
                    if 0 in _eu(ss, hold, target):
                        return False, (f"{page}: score before "
                                       f"{net.places[last]['name']}: "
                                       f"{_eu_witness(ss, hold, target)}")
                return True, ""
            run("C2", c2)
        if S.decides:
            dec = set(S.decides)
            dec_target = {v for v in range(n) if en(v, dec) > 0}
            run("C3a", lambda: af_check(dec_target, "a Decide enabling"))
            oracle["C3a_ev"] = "true" if 0 in _af(ss, dec_target, "askctl") else "false"
            run("C3b", lambda: ag_check(lambda v: en(v, dec) > 1,
                                        "two Decide occurrences enabled"))

        # ---- RF ----------------------------------------------------------
        if S.vote:
            vote = set(S.vote)
            run("D1", lambda: ag_check(
                lambda v: en(v, vote) > 0 and
                not all(cnt(v, p) > 0 for p in S.vote_socks),
                "Vote enabled with a vote missing"))
            vote_target = {v for v in range(n) if en(v, vote) > 0}
            run("D2a", lambda: af_check(vote_target, "a Vote enabling"))
            oracle["D2a_ev"] = ("true" if 0 in _af(ss, vote_target, "askctl")
                                else "false")
            run("D2b", lambda: ag_check(lambda v: cnt(v, S.pred) > 1,
                                        "more than one aggregation result"))
        return res, oracle

    # Method to read a leaf guard back as an axis-aligned box.
    @staticmethod
    def _guard_box(guard: Optional[str]):
        """Parse a conjunctive leaf guard into per-field intervals.

        Leaf guards are conjunctions of ``#f<i> x <= c`` / ``#f<i> x > c``, so a
        leaf covers a box. Catch-all guards are complements of a disjunction
        and are not boxes; None is returned for them, which is sound for the
        overlap test because a complement is disjoint from the leaves it was
        built from.

        Args:
            guard (str): The guard text.

        Returns:
            dict|None: ``{field: (low, high)}`` for ``low < x <= high``.
        """
        text = (guard or "").strip()
        if text.startswith("[") and text.endswith("]"):
            text = text[1:-1].strip()
        if not text or text.lower() == "true":
            return {}
        if re.search(r"\bnot\b|\borelse\b|\bfalse\b", text):
            return None
        box: Dict[str, List[float]] = {}
        for atom in (a.strip() for a in text.split("andalso")):
            m = re.fullmatch(r"#(f\d+)\s+x\s*(<=|<|>=|>)\s*"
                             r"\(?(~?[\d.]+(?:[eE]~?[\d+-]+)?)\)?", atom)
            if not m:
                return None
            field, op, raw = m.group(1), m.group(2), m.group(3)
            value = float(raw.replace("~", "-"))
            low, high = box.setdefault(field, [float("-inf"), float("inf")])
            if op in ("<=", "<"):
                box[field][1] = min(high, value)
            else:
                box[field][0] = max(low, value)
        return {k: tuple(v) for k, v in box.items()}

    # Method to find leaves of the same tree whose regions intersect.
    def _check_b4(self) -> PropertyResult:
        """Structural guard disjointness over the whole feature space.

        Returns:
            PropertyResult: The B4 verdict.
        """
        t0 = time.perf_counter()
        found = []
        unparsed = 0
        trans = self.cnet.transitions
        inf = float("inf")
        for page, info in self.structure.trees.items():
            boxes = []
            for ti in info["leaves"]:
                box = self._guard_box(trans[ti]["guard_text"])
                if box is None:
                    if not trans[ti]["name"].endswith("_default"):
                        unparsed += 1
                    continue
                boxes.append((trans[ti]["name"], box))
            for i in range(len(boxes)):
                for j in range(i + 1, len(boxes)):
                    (ni, bi), (nj, bj) = boxes[i], boxes[j]
                    if all(max(bi.get(f, (-inf, inf))[0], bj.get(f, (-inf, inf))[0])
                           < min(bi.get(f, (-inf, inf))[1], bj.get(f, (-inf, inf))[1])
                           for f in set(bi) | set(bj)):
                        found.append((page, ni, nj))
        elapsed = time.perf_counter() - t0
        if found:
            page, a, b = found[0]
            return PropertyResult("B4", False,
                                  f"{len(found)} overlapping leaf pair(s), first: "
                                  f"{page} {a} / {b}", elapsed)
        if unparsed:
            return PropertyResult("B4", None, f"{unparsed} leaf guard(s) are not "
                                  "conjunctions of bounds", elapsed)
        return PropertyResult("B4", True, "", elapsed)

    # ------------------------------------------------------------------
    # Conformance testing
    # ------------------------------------------------------------------

    # Method to ask the classifier for the class of every sample.
    def _model_predictions(self, classifier, xs, use_final: bool) -> List[int]:
        """Predict a batch with whatever API the object exposes.

        A :class:`RuleClassifier` and a :class:`PyRuleAnalyzer` are asked for
        the requested rule set explicitly (``use_final`` / ``use_refined``).

        Args:
            classifier: A RuleClassifier, a PyRuleAnalyzer or an estimator.
            xs (list): Record tuples.
            use_final (bool): Query the refined rule set.

        Returns:
            list: One label per sample.
        """
        import numpy as np

        names = (self.feature_names
                 or getattr(classifier, "_array_feature_names", None)
                 or getattr(classifier, "feature_names", None)
                 or [f"f{i}" for i in range(self.width)])
        matrix = np.array(xs, dtype=np.float64)
        if hasattr(classifier, "predict_batch"):
            preds = classifier.predict_batch(matrix, feature_names=list(names),
                                             use_final=use_final)
            return [int(v) for v in np.asarray(preds).ravel()]
        if hasattr(classifier, "feature_names"):
            preds = classifier.predict(matrix, use_refined=use_final)
        else:
            preds = classifier.predict(matrix)
        return [int(v) for v in np.asarray(preds).ravel()]

    # Method to compare the net's result with the classifier's on many inputs.
    def _check_pc(self, classifier, xs, use_final: bool) -> PropertyResult:
        """Conformance testing: the terminal Prediction of a run vs the model.

        Args:
            classifier: The model the net was generated from.
            xs (list): Record tuples.
            use_final (bool): Whether the net carries the refined rules.

        Returns:
            PropertyResult: The PC verdict.
        """
        t0 = time.perf_counter()
        # A classifier that rounds its inputs to float32 (as scikit-learn
        # does) is a function of the rounded values; give the net the same
        # values, as the exporter does for the sample of the initial marking.
        clf = getattr(classifier, "classifier", classifier)
        if getattr(clf, "input_dtype", None) == "float32":
            import numpy as np
            xs = [tuple(float(v) for v in np.asarray(x, dtype=np.float32))
                  for x in xs]
        try:
            got = []
            for x in xs:
                final = self.cnet.run(self.cnet.initial_marking(x))
                tokens = final[self.structure.pred]
                got.append(int(tokens[0]) if len(tokens) == 1 else None)
            expected = self._model_predictions(classifier, xs, use_final)
        except Exception as exc:
            return PropertyResult("PC", None, f"not evaluated: {exc}",
                                  time.perf_counter() - t0)
        bad = [(g, e) for g, e in zip(got, expected) if g != e]
        if bad:
            return PropertyResult("PC", False, f"{len(bad)}/{len(xs)} input(s) "
                                  f"disagree, first: net={bad[0][0]} "
                                  f"model={bad[0][1]}", time.perf_counter() - t0)
        return PropertyResult("PC", True, f"{len(xs)}/{len(xs)} inputs agree",
                              time.perf_counter() - t0)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    # Method to verify the net for one or more inputs.
    def check(self, samples=None, classifier=None, use_final: bool = True,
              test_samples=None, max_nodes: Optional[int] = None,
              verbose: bool = False) -> ModelCheckResult:
        """Verify every applicable property.

        Args:
            samples: Inputs to model check, one occurrence graph each (a sample,
                a list or a DataFrame). Defaults to the file's own initial
                marking.
            classifier: The classifier, to test prediction consistency (PC).
            use_final (bool): Whether the net carries the refined rules.
            test_samples: Inputs for conformance testing; defaults to
                ``samples``. Testing runs one maximal occurrence sequence per
                input, so it is cheap enough for a whole test set.
            max_nodes (int, optional): Occurrence-graph budget.
            verbose (bool): Print progress.

        Returns:
            ModelCheckResult: Verdicts, statistics and the expected CPN Tools
            values.
        """
        t0 = time.time()
        if max_nodes is not None:
            self.max_nodes = int(max_nodes)
        xs = self._sample_list(samples)
        merged: "collections.OrderedDict[str, PropertyResult]" = \
            collections.OrderedDict()
        stats: Dict[str, Any] = {}
        oracle: Dict[str, str] = {}
        warnings: List[str] = []
        for i, x in enumerate(xs):
            if verbose:
                print(f"  [mc] input {i + 1}/{len(xs)}")
            ss = self.state_space(x)
            if not ss.complete:
                warnings.append(f"occurrence graph exceeded {self.max_nodes} "
                                "markings: no state-space verdicts")
                for pid, spec in PROPERTY_CATALOG.items():
                    if spec.method in ("ctl", "scc") and self.family in spec.families:
                        merged.setdefault(pid, PropertyResult(
                            pid, None, "occurrence graph over budget"))
                stats = stats or {"nodes": ss.n_nodes, "arcs": ss.n_arcs,
                                  "complete": False}
                continue
            part, orc = self._evaluate(ss)
            if not stats:
                stats = {"nodes": ss.n_nodes, "arcs": ss.n_arcs,
                         "scc_nodes": ss.n_sccs, "scc_arcs": ss.n_scc_arcs,
                         "dead": len(ss.dead), "home": len(ss.home),
                         "complete": True, "generation_s": ss.elapsed}
            if x is None:
                oracle = orc
            self._merge(merged, part)

        merged["B4"] = self._check_b4()
        tested = 0
        if classifier is not None:
            pool = xs if test_samples is None else self._sample_list(test_samples)
            txs = [x if x is not None else self.own_sample for x in pool]
            merged["PC"] = self._check_pc(classifier, txs, use_final)
            tested = len(txs)

        ordered = collections.OrderedDict(
            (pid, merged[pid]) for pid in PROPERTY_CATALOG if pid in merged)
        return ModelCheckResult(self.path, self.family, ordered, stats,
                                samples=len(xs), tested=tested, warnings=warnings,
                                elapsed=time.time() - t0, oracle=oracle)

    # Method to combine the verdicts of several inputs.
    @staticmethod
    def _merge(target: Dict[str, PropertyResult], part: Dict[str, PropertyResult]):
        """Conjoin verdicts; the first counterexample found is kept.

        Args:
            target (dict): Accumulated verdicts, modified in place.
            part (dict): New verdicts.
        """
        for pid, r in part.items():
            old = target.get(pid)
            if old is None:
                target[pid] = PropertyResult(pid, r.holds, r.detail, r.elapsed)
                continue
            old.elapsed += r.elapsed
            if old.holds is False:
                continue
            if r.holds is False:
                old.holds, old.detail = False, r.detail
            elif old.holds is None:
                old.holds, old.detail = r.holds, r.detail

    # ------------------------------------------------------------------
    # CPN Tools
    # ------------------------------------------------------------------

    # Method to produce the ASK-CTL program that asks CPN Tools the same questions.
    def ml_program(self) -> Tuple[str, "collections.OrderedDict[str, str]"]:
        """The CPN ML declarations and queries matching :meth:`_evaluate`.

        Every query is a string-valued ML expression, evaluated after entering
        the state-space tool, calculating the occurrence and SCC graphs and
        loading ASK-CTL. The keys are those of :attr:`ModelCheckResult.oracle`.

        Returns:
            tuple: ``(declarations, {key: expression})``.
        """
        S = self.structure
        net = self.cnet
        top = S.top

        def mark(pidx):
            p = net.places[pidx]
            return f"(fn n => size (Mark.{p['page']}'{p['name']} 1 n))"

        def group_fun(name, tis):
            cases = " | ".join(
                f"Bind.{net.transitions[ti]['page']}'{net.transitions[ti]['name']} _ "
                f"=> true" for ti in tis)
            return f"fun {name} a = case ArcToBE a of {cases} | _ => false;"

        decl: List[str] = []
        decl.append("val DEAD = NOT(MODAL(TT));")
        decl.append(f"fun nPred n = size (Mark.{top}'Prediction 1 n);")
        decl.append('val PRED = NF("predicted", fn n => nPred n > 0);')
        decl.append("fun AFmax phi = AND(EV(phi), "
                    "NOT(EXIST_UNTIL(NOT(phi), AND(DEAD, NOT(phi)))));")
        decl.append("fun enCount isT n = length (List.filter isT (OutArcs n));")
        decl.append('fun EN isT = NF("enabled", fn n => enCount isT n > 0);')
        decl.append('fun MK f = NF("marked", fn (n : Node) => (f n : int) > 0);')
        decl.append("val allMarks = [" + ", ".join(mark(i) for i in
                                                    range(len(net.places))) + "];")
        if self.labels is not None:
            decl.append("val LABELS = [" + ", ".join(str(k) for k in self.labels)
                        + "];")
            decl.append(f"fun validLabels n = let val m = Mark.{top}'Prediction 1 n "
                        "in size m = List.foldl (fn (k, acc) => acc + cf (k, m)) 0 "
                        "LABELS end;")
        tree_names = []
        for i, info in enumerate(S.trees.values()):
            decl.append(group_fun(f"isLeaf{i}", info["leaves"]))
            tree_names.append(f"isLeaf{i}")
        if tree_names:
            decl.append("val leafGroups = [" + ", ".join(tree_names) + "];")
            outs = [info["out"] for info in S.trees.values() if info["out"] is not None]
            decl.append("val treeOuts = [" + ", ".join(mark(p) for p in outs) + "];")
        if S.channels:
            pairs = [(a, b) for ch in S.channels.values()
                     for a, b in zip(ch["acc"], ch["acc"][1:])]
            decl.append("val accPairs = [" + ", ".join(
                f"({mark(a)}, {mark(b)})" for a, b in pairs) + "];")
            scores = [(ch["acc"][-1], ch["score"]) for ch in S.channels.values()
                      if ch["acc"] and ch["score"] is not None]
            decl.append("val scorePairs = [" + ", ".join(
                f"({mark(a)}, {mark(b)})" for a, b in scores) + "];")
        if S.decides:
            decl.append(group_fun("isDecide", S.decides))
        if S.vote:
            decl.append(group_fun("isVote", S.vote))
            decl.append("val voteMarks = [" + ", ".join(
                mark(p) for p in S.vote_socks) + "];")

        def ev(formula):
            return f"Bool.toString (eval_node ({formula}) InitNode)"

        q: "collections.OrderedDict[str, str]" = collections.OrderedDict()
        q["nodes"] = "Int.toString (NoOfNodes ())"
        q["arcs"] = "Int.toString (NoOfArcs ())"
        q["scc_nodes"] = "Int.toString (SccNoOfNodes ())"
        q["scc_arcs"] = "Int.toString (SccNoOfArcs ())"
        q["dead"] = "Int.toString (length (ListDeadMarkings ()))"
        q["home"] = "Int.toString (length (ListHomeMarkings ()))"
        q["A1"] = ev("EV(DEAD)")
        q["A2"] = ev("NOT(POS(AND(DEAD, NOT(PRED))))")
        q["A3"] = ev("AFmax PRED")
        q["A3_ev"] = ev("EV(PRED)")
        q["A4"] = ev("INV(POS(PRED))")
        q["A5"] = ev('INV(NF("one prediction", fn n => nPred n <= 1))')
        if self.labels is not None:
            q["A6"] = ev('INV(NF("valid labels", validLabels))')
        q["A7"] = ev('INV(NF("safe", fn n => List.all (fn f => f n <= 1) allMarks))')
        q["A8"] = "Bool.toString (length (ListHomeMarkings ()) > 0)"
        if tree_names:
            q["B1"] = ev('INV(NF("leaf determinism", fn n => List.all '
                         '(fn isT => enCount isT n <= 1) leafGroups))')
            q["B2"] = ("Bool.toString (List.all (fn isT => eval_node "
                       "(AFmax (EN isT)) InitNode) leafGroups)")
            q["B2_ev"] = ("Bool.toString (List.all (fn isT => eval_node "
                          "(EV (EN isT)) InitNode) leafGroups)")
            q["B3"] = ev('INV(NF("tree outputs", fn n => List.all '
                         '(fn f => f n <= 1) treeOuts))')
        if S.channels:
            q["C1"] = ("Bool.toString (List.all (fn (a, b) => eval_node "
                       "(NOT(EXIST_UNTIL(NOT(MK a), MK b))) InitNode) accPairs)")
            q["C2"] = ("Bool.toString (List.all (fn (a, b) => eval_node "
                       "(NOT(EXIST_UNTIL(NOT(MK a), MK b))) InitNode) scorePairs)")
        if S.decides:
            q["C3a"] = ev("AFmax (EN isDecide)")
            q["C3a_ev"] = ev("EV (EN isDecide)")
            q["C3b"] = ev('INV(NF("one decision", fn n => enCount isDecide n <= 1))')
        if S.vote:
            q["D1"] = ev('INV(OR(NOT(EN isVote), NF("all votes", fn n => '
                         'List.all (fn f => f n > 0) voteMarks)))')
            q["D2a"] = ev("AFmax (EN isVote)")
            q["D2a_ev"] = ev("EV (EN isVote)")
            q["D2b"] = ev('INV(NF("one aggregation", fn n => nPred n <= 1))')
        return "\n".join(decl), q

    # Method to write the ASK-CTL script matching this model for CPN Tools.
    def export_askctl(self, filepath: str) -> str:
        """Write a CPN Tools script that asks every question of :meth:`check`.

        Open the net in CPN Tools, apply *Enter State Space* from the State
        Space palette, then evaluate ``use "<this file>";`` in an auxiliary
        text. The script computes the occurrence and SCC graphs itself and ends
        with a string holding one ``key=value`` per line, with the keys of
        :attr:`ModelCheckResult.oracle`.

        Args:
            filepath (str): Destination ``.sml`` path.

        Returns:
            str: The path written.
        """
        decl, queries = self.ml_program()
        out = [
            "(* ASK-CTL cross-check generated by pyRuleAnalyzer for",
            f"   {os.path.basename(self.path)} ({self.family}).",
            "   1. open the net in CPN Tools and apply Enter State Space;",
            "   2. evaluate  use \"<this file>\";  in an auxiliary text.",
            "   AFmax phi encodes the textbook AF phi: ASK-CTL's EV is vacuously",
            "   true at dead markings, so EV alone would accept a net that",
            "   deadlocks before phi. *)",
            "",
            'use (ogpath ^ "ASKCTL/ASKCTLloader.sml");',
            "CalculateOccGraph ();",
            "CalculateSccGraph ();",
            "",
            decl,
            "",
            "val PYRA_RESULTS = [",
            ",\n".join(f'  ("{k}", {v})' for k, v in queries.items()),
            "];",
            'val PYRA_REPORT = String.concat (map (fn (k, v) => k ^ "=" ^ v ^ "\\n")'
            " PYRA_RESULTS);",
            "print PYRA_REPORT;",
            "PYRA_REPORT;",
        ]
        directory = os.path.dirname(os.path.abspath(filepath))
        os.makedirs(directory, exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as fh:
            fh.write("\n".join(out) + "\n")
        return filepath


# ---------------------------------------------------------------------------
# Convenience functions
# ---------------------------------------------------------------------------

# Function to model check a generated .cpn file in one call.
def check_cpn(path: str, samples=None, classifier=None,
              feature_names: Optional[Sequence[str]] = None,
              class_labels: Optional[Sequence[int]] = None,
              use_final: bool = True, test_samples=None,
              max_nodes: int = DEFAULT_MAX_NODES,
              verbose: bool = False) -> ModelCheckResult:
    """Verify a generated ``.cpn`` model.

    Args:
        path (str): The ``.cpn`` file.
        samples: Inputs to model check (defaults to the file's own).
        classifier: Classifier for the conformance test.
        feature_names (list, optional): Ordered feature names.
        class_labels (list, optional): Label domain for A6.
        use_final (bool): Whether the net carries the refined rules.
        test_samples: Inputs for conformance testing.
        max_nodes (int): Occurrence-graph budget.
        verbose (bool): Print progress.

    Returns:
        ModelCheckResult: Verdicts and statistics.
    """
    checker = CPNModelChecker(path, feature_names=feature_names,
                              class_labels=class_labels, max_nodes=max_nodes)
    return checker.check(samples=samples, classifier=classifier,
                         use_final=use_final, test_samples=test_samples,
                         verbose=verbose)


# Function to compare the verdicts of the initial and the refined model.
def compare_results(initial: ModelCheckResult, final: ModelCheckResult) -> str:
    """Side-by-side report of two runs; the acceptance test of a refinement.

    Args:
        initial (ModelCheckResult): Verdicts for the unrefined model.
        final (ModelCheckResult): Verdicts for the refined model.

    Returns:
        str: The comparison, listing every regression.
    """
    ids = [pid for pid in PROPERTY_CATALOG
           if pid in initial.properties or pid in final.properties]
    lines = ["Initial vs. refined model", "=" * 76,
             f"  {'ID':<5}{'PROPERTY':<30}{'METHOD':<12}{'INITIAL':<9}"
             f"{'REFINED':<9}RESULT", "  " + "-" * 74]
    regressions = []
    for pid in ids:
        a, b = initial.properties.get(pid), final.properties.get(pid)
        sa = a.status if a else "n/a"
        sb = b.status if b else "n/a"
        verdict = "same"
        if a and b and a.holds is True and b.holds is False:
            verdict = "REGRESSION"
            regressions.append((pid, b.detail))
        elif a and b and a.holds is False and b.holds is True:
            verdict = "fixed"
        elif (a and a.holds is None) or (b and b.holds is None):
            verdict = "not compared"
        spec = PROPERTY_CATALOG[pid]
        lines.append(f"  {pid:<5}{spec.name:<30}{spec.method:<12}{sa:<9}{sb:<9}"
                     f"{verdict}")
    lines.append("")
    if regressions:
        lines.append(f"  {len(regressions)} property(ies) broken by the refinement:")
        for pid, detail in regressions:
            lines.append(f"    {pid}: {detail}")
    else:
        lines.append("  the refinement preserved every verified property")
    return "\n".join(lines)
